# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WatchApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WatchApp
  pod 'CocoaAsyncSocket'  
  pod ‘RNCryptor-objc’

end

target 'WatchApp WatchKit App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WatchApp WatchKit App

end

target 'WatchApp WatchKit Extension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WatchApp WatchKit Extension

end
